name: chat_pickers
description: A new Flutter package for displaying a keyboard for using emojis/gifs.
version: 0.2.3
homepage: "https://github.com/kfiross/chat_pickers"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.3
  giphy_client: #WAS: ^0.2.0        # for giphy picker
    git: https://github.com/bottlepay/giphy_client.git

  #  shared_preferences: ^0.5.12+4      # for keeping recent picked emojies
  material_design_icons_flutter: ^5.0.5955-rc.1    # for icons

  # base package implementation of choosing emojies on each platform
#  emoji_picker: ^0.1.0   # native-no-nullsafty
  emoji_picker_flutter: ^1.0.6

  flutter_hooks: ^0.16.0
  universal_io: ^2.0.4    # for work on web

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

